### ISSUE TITLE
Should we remove the stateful location from components?

### ISSUE THREAD

**Issue by kamry-bowman** [Lambda-School-Labs/labs9-employee-scheduler#116]
It looks like we have a breadcrumb based on stateful location in the components. But it seems like the location of a component is relatively unchanging, so I'm not sure if it's appropriate to have it on state

A bunch of the "view" components look like this, wanted to get others thoughts

```
class CreateSchedule extends Component {
  state = {
    location: 'Schedule'
  }
  render() {
    return (
      <div>
        <LeftSideBar />
        <BreadCrumb location={this.state.location} />
      </div>
    )
  }
}
```

**Comment by CLantigua2** [comment]
This was meant to be a temporary solution for the bread crumbs. I'll replace it with a string for now as that should make it easier to follow.

**Comment by CLantigua2** [comment]
state removed and passed as a string. Should now appear as: <BreactCrumb location ="Location" />
Stateless components changed to functions.
