### ISSUE TITLE
Mix-up in Time Off component?

### ISSUE THREAD

**Issue by rd825** [Lambda-School-Labs/labs9-employee-scheduler#189]
I think “confirmed”  is coming from the seeds in the DB and “approved” is in the front end logic.  We just need to decide which word we want to use and make it consistent on both ends.

 ---
name: Approved vs. Confirmed in TimeOff
about: Currently there is a mysterious "confirmed" status for some PTO requests. This should not exist, the proper states for a request are "approved, denied, and pending"

---

## Bug Report

**Current Behavior**
see above. Here's a screenshot: https://gyazo.com/213a2af25fcc1fd75f19ffea0f26205c

**Expected behavior/code**
The issue is that "confirmed" doesn't bring up buttons to then "unconfirm" (i.e. deny) the PTO.

**Comment by adamhinckley** [comment]
I fixed this to only use the word "approved" on both the front and backend.
