### ISSUE TITLE
Logout should clear entire redux store...

### ISSUE THREAD

**Issue by kamry-bowman** [Lambda-School-Labs/labs9-employee-scheduler#250]
---
name: 🐛 Bug Report
![image](https://user-images.githubusercontent.com/37093582/51721184-ddd68d00-200d-11e9-8124-c1236ad31760.png)

Even after we logout, everything exists on state in redux. I'm not sure how vulnerable per se that situation is, I would say not much, but it does mean that if we log out, then log in again, there is a brief moment where when the shift-scheduler loads, old data is visible before the store clears from axios. Not a great look imo

Can probably fix by just firing off additional reset actions from logout action creator.

**Comment by CLantigua2** [comment]
bug fixed in PR #257 
https://github.com/Lambda-School-Labs/labs9-employee-scheduler/pull/257
