### ISSUE TITLE
Get days to show up in order for employee availability

### ISSUE THREAD

**Issue by adamhinckley** [Lambda-School-Labs/labs9-employee-scheduler#270]
![screen shot 2019-01-25 at 3 33 31 pm](https://user-images.githubusercontent.com/40447332/51776503-bb4c7e80-20b6-11e9-8690-b9a7af3eb70b.png)

**Comment by rd825** [comment]
I have a sort method for days that might work in WeeklySummary.js

**Comment by rd825** [comment]
I think @kamry-bowman fixed this
