### ISSUE TITLE
tooltip for the employees needs z index adjusted so the lines of the calendar go behind it.

### ISSUE THREAD

**Issue by adamhinckley** [Lambda-School-Labs/labs9-employee-scheduler#299]
@rd825 asked for this 😄 

![screen shot 2019-01-29 at 10 47 37 am](https://user-images.githubusercontent.com/40447332/51931593-74ae9b00-23ba-11e9-9775-fb8c5719c7ba.png)

**Comment by rd825** [comment]
Tooltips removed in favor of demo.
